// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HowsGoingCore.Models;

public partial class Friendrequest
{
    public int FriendrequestId { get; set; }

    public string User1 { get; set; }

    public string User2 { get; set; }

    public virtual HowsUser User1Navigation { get; set; }

    public virtual HowsUser User2Navigation { get; set; }
}