// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HowsGoingCore.Models;

public partial class Friendrequest
{
    public int FriendrequestId { get; set; }

    public string RequestReceiver { get; set; }

    public string RequestSender { get; set; }

    public virtual HowsUser RequestReceiverNavigation { get; set; }

    public virtual HowsUser RequestSenderNavigation { get; set; }
}